runtime: nodejs16
service: default
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1
  max_concurrent_requests: 70

handlers:
  - url: /.*
    secure: always
    script: auto
