version: '3'

services:
  hako:
    build: .
    command: npm run dev
    volumes:
      - .:/src
    ports:
      - 8123:8123
    environment:
      - PORT=8123
      - GOOGLE_CLOUD_PROJECT=hako-310708
      - GOOGLE_APPLICATION_CREDENTIALS=hako-310708-034cecbf3b1b.json
